In [1]:
import pandas as pd
import numpy as np

In [2]:
raw=pd.read_csv("/global/scratch/users/jennaisrael/expanse_scenario_files/station_list/station.in.run27-",sep=" ",skiprows=2,header=None)
raw

,0,1,2,3,4,5,6
0,1,605075.100000,4.208475e+06,-0.5,!,anh2,default San Joaquin at Antioch
1,2,636491.300000,4.235315e+06,-0.5,!,ben,default Mokelumne River at Benson's Ferry
2,3,609500.300000,4.239525e+06,-0.5,!,ccs,default Cache Slough
3,4,603778.350000,4.287183e+06,-0.5,!,ccy,default Cache Creek at Yolo
4,5,628727.800000,4.189748e+06,-0.5,!,cis,default Old River at Coney Island
...,...,...,...,...,...,...,...
403,404,629284.727922,4.192510e+06,-0.5,!,Y51,replace_Yu_51
404,405,629640.700313,4.207061e+06,-0.5,!,Y40,replace_Yu_40
405,406,631559.000000,4.236277e+06,-0.5,!,R1,Rec_Delta_Meadows
406,407,630882.000000,4.235051e+06,-0.5,!,R2,Rec_Locke
407,408,630084.000000,4.241117e+06,-0.5,!,R3,Rec_East_Courtland

In [3]:
# need to split the last column into 2 bc batch metrics is expecting 2 columns
six=np.array([])
seven=np.array([])
for s in raw[6]:
    if " " in s and "JT" not in s:
        first=s.split()[0]
        sec=' '.join(s.split()[1:])
        #print(sec)
    else:
        first='default'
        sec=s
    # #print(first)
    six=np.append(six,first)
    seven=np.append(seven,sec)

In [4]:
clean=raw.iloc[:,0:5]
clean[6]=six
clean[7]=seven
clean

,0,1,2,3,4,6,7
0,1,605075.100000,4.208475e+06,-0.5,!,default,San Joaquin at Antioch
1,2,636491.300000,4.235315e+06,-0.5,!,default,Mokelumne River at Benson's Ferry
2,3,609500.300000,4.239525e+06,-0.5,!,default,Cache Slough
3,4,603778.350000,4.287183e+06,-0.5,!,default,Cache Creek at Yolo
4,5,628727.800000,4.189748e+06,-0.5,!,default,Old River at Coney Island
...,...,...,...,...,...,...,...
403,404,629284.727922,4.192510e+06,-0.5,!,default,replace_Yu_51
404,405,629640.700313,4.207061e+06,-0.5,!,default,replace_Yu_40
405,406,631559.000000,4.236277e+06,-0.5,!,default,Rec_Delta_Meadows
406,407,630882.000000,4.235051e+06,-0.5,!,default,Rec_Locke
407,408,630084.000000,4.241117e+06,-0.5,!,default,Rec_East_Courtland

In [7]:
#clean.to_csv("./station.in.run_27-.fix",sep=' ',index = False)