In [1]:
import numpy as np
import pandas as pd

In [2]:
old=pd.read_csv("/global/scratch/users/jennaisrael/expanse_scenario_files/station_list/station.in.run_27-.fix",sep=" ",skiprows=2,header=None)
old

,0,1,2,3,4,5,6,7
0,1,605075.100000,4.208475e+06,-0.5,!,anh2,default,San Joaquin at Antioch
1,2,636491.300000,4.235315e+06,-0.5,!,ben,default,Mokelumne River at Benson's Ferry
2,3,609500.300000,4.239525e+06,-0.5,!,ccs,default,Cache Slough
3,4,603778.350000,4.287183e+06,-0.5,!,ccy,default,Cache Creek at Yolo
4,5,628727.800000,4.189748e+06,-0.5,!,cis,default,Old River at Coney Island
...,...,...,...,...,...,...,...,...
403,404,629284.727922,4.192510e+06,-0.5,!,Y51,default,replace_Yu_51
404,405,629640.700313,4.207061e+06,-0.5,!,Y40,default,replace_Yu_40
405,406,631559.000000,4.236277e+06,-0.5,!,R1,default,Rec_Delta_Meadows
406,407,630882.000000,4.235051e+06,-0.5,!,R2,default,Rec_Locke
407,408,630084.000000,4.241117e+06,-0.5,!,R3,default,Rec_East_Courtland

In [3]:
old.set_index(old[0],inplace=True)
old

,0,1,2,3,4,5,6,7
0,,,,,,,,
1,1,605075.100000,4.208475e+06,-0.5,!,anh2,default,San Joaquin at Antioch
2,2,636491.300000,4.235315e+06,-0.5,!,ben,default,Mokelumne River at Benson's Ferry
3,3,609500.300000,4.239525e+06,-0.5,!,ccs,default,Cache Slough
4,4,603778.350000,4.287183e+06,-0.5,!,ccy,default,Cache Creek at Yolo
5,5,628727.800000,4.189748e+06,-0.5,!,cis,default,Old River at Coney Island
...,...,...,...,...,...,...,...,...
404,404,629284.727922,4.192510e+06,-0.5,!,Y51,default,replace_Yu_51
405,405,629640.700313,4.207061e+06,-0.5,!,Y40,default,replace_Yu_40
406,406,631559.000000,4.236277e+06,-0.5,!,R1,default,Rec_Delta_Meadows
407,407,630882.000000,4.235051e+06,-0.5,!,R2,default,Rec_Locke
408,408,630084.000000,4.241117e+06,-0.5,!,R3,default,Rec_East_Courtland

In [4]:
new=pd.read_csv("/global/scratch/users/jennaisrael/expanse_scenario_files/station_list/2026_05_stations_from_Justin.csv")
new

,STATION #,REGION,Long Name,ORIGIN,X,Y,Short Name,Archive Index
0,13,Central Bay,San Francisco Bay near Coyote Point,ECO,561435.7,4161086.0,ECO8,NaN
1,14,Central Bay,South Central San Francisco Bay,ECO,565890.6,4164982.0,ECO9,NaN
2,15,Central Bay,San Francisco Bay at San Lorenzo,ECO,572889.2,4168419.0,ECO10,NaN
3,16,Central Bay,Central San Francisco Bay,ECO,562701.6,4170024.0,ECO11,NaN
4,17,Central Bay,South East of Bay View,ECO,556269.1,4172028.0,ECO12,NaN
...,...,...,...,...,...,...,...,...
418,87,Suisun Bay,Montezuma Slough at Roaring River,DWR,597578.3,4216762.7,msl,258.0
419,88,Suisun Bay,Suisun Bay At Van Sickle Island,DWR,597605.9,4211894.6,confl,218.0
420,89,Suisun Bay,Sacramento River near Montezuma Slough,EJ,599775.3,4213937.9,EJ10,NaN
421,90,Suisun Bay,Collinsville,DWR,600858.7,4214644.1,cll,82.0
422,91,Suisun Bay,Sacramento River at Collinsville,DWR,600859.1,4214643.6,cse,48.0

In [5]:
new['X']=new['X'].astype(np.float64)
new['Y']=new['Y'].astype(np.float64)

In [6]:
# which stations have an archive index
original=new[new['Archive Index'].notnull()]
ind=original['Archive Index'].values.astype(np.int64)
ind

array([ 77, 241,  74, 185,  72, 182,  71,  79, 381, 378, 379, 107, 323,
       321, 322,  13,  34, 324, 372, 325, 171, 167, 326, 328, 203, 403,
       169, 396,   7, 340, 106,  17, 168,  19,  30, 108, 111, 373, 306,
       305, 304,  33,   5,  99, 358, 404, 152, 100,  47, 156, 154, 347,
       343, 272, 327, 345,  97, 368, 143, 251,  67, 344, 280,   1, 281,
       399, 201,   9, 187, 172, 398,  38, 116, 129, 148, 149, 115,  87,
       200, 109, 198, 336, 196, 317, 316, 320,  35, 145, 110, 114, 319,
       365, 288,  37, 113, 401, 332, 393, 333, 215,   3, 394, 219, 395,
       216, 191, 126, 269, 189, 265, 177, 271, 231, 124, 128, 270, 127,
       229, 266, 267, 217, 264, 123, 224, 211, 329, 212, 331, 195, 125,
       334, 214, 380, 318, 208, 165,  59, 213, 361, 119, 355, 118, 374,
       337, 309, 389, 287, 314, 315, 377, 360, 376,  15, 400, 392, 350,
       362, 351, 147, 353, 391, 387, 385, 308, 122,  50, 120, 121, 146,
       408, 144, 311, 312, 310, 352, 194, 117, 112, 407, 406, 313, 192,
       364, 397, 348, 339,   2, 307, 138,  73, 132, 140, 233, 236, 234,
        78,  91,  32, 157,  43,   6,  60,  61, 159,  29, 375,  98, 382,
       302, 247, 295, 294, 293, 298, 299, 383,  27, 166, 346, 354,  70,
       150, 292, 181,   8, 349, 207, 291, 180,  41,  39, 290, 249, 289,
       366, 359, 183,  25, 384, 155, 297, 370, 390, 341,  44,  42, 300,
       301, 356,  40, 357, 371, 342,  96,  31,  66,  65, 388, 184, 253,
        26, 252, 335, 386, 369, 338,  95,  52, 130, 242,  58, 197,  55,
       255,  54, 256, 142, 221, 220, 257,  56, 206, 227,  89, 262, 259,
       205,  57, 278, 204,  23, 254,  85,  63, 258, 218,  82,  48])

# Are the coordinates of the points the same?

In [7]:
original.set_index(original['Archive Index'].astype(np.int64),inplace=True)

In [9]:
for d in ind:
    if abs(original['X'].loc[d]-old[1].loc[d])>0.05 or (original['Y'].loc[d]-old[2].loc[d])>0.05:
        
        if original['Short Name'].loc[d]== old[5].loc[d]:
            print(original['X'].loc[d])
            print(old[1].loc[d])
            # print(original['Y'].loc[d].type)
            # print(old[2].loc[d].type)
            print('Archive station index '+ str(d)+' has moved')
            print(original['Short Name'].loc[d])
            #and then fix it by adding RE to the front 
            new=new.replace(original['Short Name'].loc[d],'RE'+original['Short Name'].loc[d])
            
        #print(old[5].loc[d])

634779.5
634779.45
Archive station index 272 has moved
mrx
605331.3
605332.154222639
Archive station index 401 has moved
Y173
614201.1
614165.7
Archive station index 191 has moved
lir
615783.5
615789.9
Archive station index 177 has moved
fre
586071.3
586311.2
Archive station index 233 has moved
coy
648081.1
648060.2
Archive station index 184 has moved
sjd
582199.0
582201.45
Archive station index 142 has moved
bts

# if the locations are different add a new row

In [10]:
toadd=np.array([]) # justin's station numbers to add 
for d in ind:
    if abs(original['X'].loc[d]-old[1].loc[d])>0.05 or (original['Y'].loc[d]-old[2].loc[d])>0.05:
        toadd=np.append(original['STATION #'].loc[d],toadd).astype(np.int64)

In [11]:
print(len(toadd))
toadd

63

array([ 84,  65,  60,  59,  52, 424, 423, 422, 421, 417, 416, 412, 411,
       410, 402, 373, 372, 367, 365, 357,   4,   1, 248, 235, 220, 218,
       216, 214, 211, 210, 206, 205, 199, 198, 196, 194, 192, 187, 157,
       152, 149, 147, 142, 140, 136, 135, 129, 123, 114, 109, 100, 334,
       332, 329, 326, 323, 316, 312, 289, 258, 257,  28,  21])

In [12]:
moretoadd=new[new['Archive Index'].isnull()]['STATION #'].values
moretoadd

array([ 13,  14,  15,  16,  17,  18,  19,  20,  25,  26,  27, 263, 265,
       266, 269, 270, 276, 279, 280, 281, 282, 285, 291, 292, 296, 299,
       305, 308, 309, 314, 315, 317, 319, 320, 321, 324, 327, 331, 335,
       336, 337, 339, 340, 341, 342, 344, 345, 348, 349, 350, 351, 352,
       353,  92,  93,  95,  98,  99, 101, 103, 106, 108, 110, 112, 119,
       128, 130, 137, 145, 151, 173, 183, 185, 186, 191, 195, 200, 201,
       203, 208, 217, 230, 234, 240, 241, 245, 247, 249, 251, 252, 253,
       254,  33,  35,  36,  37,  38,  39,  41,  43,  44,  45,  46,   2,
         3,   7,   8,   9,  10,  12, 355,  47,  48,  53,  58,  61,  64,
        69,  73,  74,  76,  77,  81,  83,  89])

In [13]:
type(toadd[0])

numpy.int64

In [14]:
alltoadd=np.concatenate([toadd,moretoadd])
alltoadd

array([ 84,  65,  60,  59,  52, 424, 423, 422, 421, 417, 416, 412, 411,
       410, 402, 373, 372, 367, 365, 357,   4,   1, 248, 235, 220, 218,
       216, 214, 211, 210, 206, 205, 199, 198, 196, 194, 192, 187, 157,
       152, 149, 147, 142, 140, 136, 135, 129, 123, 114, 109, 100, 334,
       332, 329, 326, 323, 316, 312, 289, 258, 257,  28,  21,  13,  14,
        15,  16,  17,  18,  19,  20,  25,  26,  27, 263, 265, 266, 269,
       270, 276, 279, 280, 281, 282, 285, 291, 292, 296, 299, 305, 308,
       309, 314, 315, 317, 319, 320, 321, 324, 327, 331, 335, 336, 337,
       339, 340, 341, 342, 344, 345, 348, 349, 350, 351, 352, 353,  92,
        93,  95,  98,  99, 101, 103, 106, 108, 110, 112, 119, 128, 130,
       137, 145, 151, 173, 183, 185, 186, 191, 195, 200, 201, 203, 208,
       217, 230, 234, 240, 241, 245, 247, 249, 251, 252, 253, 254,  33,
        35,  36,  37,  38,  39,  41,  43,  44,  45,  46,   2,   3,   7,
         8,   9,  10,  12, 355,  47,  48,  53,  58,  61,  64,  69,  73,
        74,  76,  77,  81,  83,  89])

In [15]:
len(alltoadd)

188

In [16]:
new.set_index(new['STATION #'],inplace=True)

In [17]:
new

,STATION #,REGION,Long Name,ORIGIN,X,Y,Short Name,Archive Index
STATION #,,,,,,,,
13,13,Central Bay,San Francisco Bay near Coyote Point,ECO,561435.7,4161086.0,ECO8,NaN
14,14,Central Bay,South Central San Francisco Bay,ECO,565890.6,4164982.0,ECO9,NaN
15,15,Central Bay,San Francisco Bay at San Lorenzo,ECO,572889.2,4168419.0,ECO10,NaN
16,16,Central Bay,Central San Francisco Bay,ECO,562701.6,4170024.0,ECO11,NaN
17,17,Central Bay,South East of Bay View,ECO,556269.1,4172028.0,ECO12,NaN
...,...,...,...,...,...,...,...,...
87,87,Suisun Bay,Montezuma Slough at Roaring River,DWR,597578.3,4216762.7,msl,258.0
88,88,Suisun Bay,Suisun Bay At Van Sickle Island,DWR,597605.9,4211894.6,confl,218.0
89,89,Suisun Bay,Sacramento River near Montezuma Slough,EJ,599775.3,4213937.9,EJ10,NaN
90,90,Suisun Bay,Collinsville,DWR,600858.7,4214644.1,cll,82.0
91,91,Suisun Bay,Sacramento River at Collinsville,DWR,600859.1,4214643.6,cse,48.0

In [19]:
newtoadd=new.loc[alltoadd].drop(columns=
    ['STATION #','REGION','ORIGIN','Archive Index']).rename(
    columns={'Long Name': 7,'X':1,'Y':2,'Short Name':5})
#rename the columns
newtoadd

                                                7         1          2      5
STATION #
84                       Blacklock (NE1)           595735.3  4226395.8  REbll
65           Hunter Cut at Montezuma Slough        582986.8  4223473.0  REhun
60                        Boynton Slough           582199.0  4228990.9  REbts
59            Godfather II on Suisun Slough        580585.9  4220050.9  REgod
52             Cordelia Slough at Ibis club        577637.4  4223643.4  REibs
...                                           ...       ...        ...    ...
76                          Suisun Bay West Reach  588097.3  4212803.8    EJ6
77                    Suisun Bay near Snag Island  588959.7  4214252.7    EJ7
81             Montezuma Slough near Cross Slough  593349.7  4224951.8    EJ8
83              Montezuma Slough at Meins Landing  595597.5  4221857.0    EJ9
89         Sacramento River near Montezuma Slough  599775.3  4213937.9   EJ10

[188 rows x 4 columns]

In [29]:
#put an E infront of the short names that don't have any numbers
for s in newtoadd[5]:
    if s[0]=='5':
        newtoadd[5]=newtoadd[5].replace(s,'E'+str(s))

In [30]:
newtoadd[3]=newtoadd[1]*0-0.5
newtoadd[4]='!'
newtoadd[6]='default'
newtoadd

,7,1,2,5,3,4,6,0
0,,,,,,,,
409,Blacklock (NE1),595735.3,4226395.8,REbll,-0.5,!,default,409
410,Hunter Cut at Montezuma Slough,582986.8,4223473.0,REhun,-0.5,!,default,410
411,Boynton Slough,582199.0,4228990.9,REbts,-0.5,!,default,411
412,Godfather II on Suisun Slough,580585.9,4220050.9,REgod,-0.5,!,default,412
413,Cordelia Slough at Ibis club,577637.4,4223643.4,REibs,-0.5,!,default,413
...,...,...,...,...,...,...,...,...
592,Suisun Bay West Reach,588097.3,4212803.8,EJ6,-0.5,!,default,592
593,Suisun Bay near Snag Island,588959.7,4214252.7,EJ7,-0.5,!,default,593
594,Montezuma Slough near Cross Slough,593349.7,4224951.8,EJ8,-0.5,!,default,594
595,Montezuma Slough at Meins Landing,595597.5,4221857.0,EJ9,-0.5,!,default,595
596,Sacramento River near Montezuma Slough,599775.3,4213937.9,EJ10,-0.5,!,default,596

In [31]:
newtoadd[0]=np.arange(409,409+len(newtoadd))
newtoadd

,7,1,2,5,3,4,6,0
0,,,,,,,,
409,Blacklock (NE1),595735.3,4226395.8,REbll,-0.5,!,default,409
410,Hunter Cut at Montezuma Slough,582986.8,4223473.0,REhun,-0.5,!,default,410
411,Boynton Slough,582199.0,4228990.9,REbts,-0.5,!,default,411
412,Godfather II on Suisun Slough,580585.9,4220050.9,REgod,-0.5,!,default,412
413,Cordelia Slough at Ibis club,577637.4,4223643.4,REibs,-0.5,!,default,413
...,...,...,...,...,...,...,...,...
592,Suisun Bay West Reach,588097.3,4212803.8,EJ6,-0.5,!,default,592
593,Suisun Bay near Snag Island,588959.7,4214252.7,EJ7,-0.5,!,default,593
594,Montezuma Slough near Cross Slough,593349.7,4224951.8,EJ8,-0.5,!,default,594
595,Montezuma Slough at Meins Landing,595597.5,4221857.0,EJ9,-0.5,!,default,595
596,Sacramento River near Montezuma Slough,599775.3,4213937.9,EJ10,-0.5,!,default,596

In [32]:
newtoadd.set_index(newtoadd[0],inplace=True)

In [33]:
#full=old.copy()
full=pd.concat([old,newtoadd])
full

,0,1,2,3,4,5,6,7
0,,,,,,,,
1,1,605075.10,4208474.7,-0.5,!,anh2,default,San Joaquin at Antioch
2,2,636491.30,4235314.6,-0.5,!,ben,default,Mokelumne River at Benson's Ferry
3,3,609500.30,4239525.4,-0.5,!,ccs,default,Cache Slough
4,4,603778.35,4287183.0,-0.5,!,ccy,default,Cache Creek at Yolo
5,5,628727.80,4189748.3,-0.5,!,cis,default,Old River at Coney Island
...,...,...,...,...,...,...,...,...
592,592,588097.30,4212803.8,-0.5,!,EJ6,default,Suisun Bay West Reach
593,593,588959.70,4214252.7,-0.5,!,EJ7,default,Suisun Bay near Snag Island
594,594,593349.70,4224951.8,-0.5,!,EJ8,default,Montezuma Slough near Cross Slough
595,595,595597.50,4221857.0,-0.5,!,EJ9,default,Montezuma Slough at Meins Landing
596,596,599775.30,4213937.9,-0.5,!,EJ10,default,Sacramento River near Montezuma Slough

In [35]:
full.to_csv("./station.in.May2026",sep=' ',index = False)

In [9]:
old.loc[[10,20],:]

,0,1,2,3,4,5,6,7
0,,,,,,,,
10,10,610598.8,4215917.6,-20.0,!,emm2,lower,Sacramento River at Emmaton
20,20,613977.7,4206196.5,-0.5,!,inb,default,CCWD Rock Slough PP

In [11]:
# check if the short name is the same for the indices that should be in the old list
overlap=old.loc[ind,5]
overlap

0
77     aamc1
241    sfp17
74     sffpx
185      alk
72     tibc1
       ...
63       nsl
258      msl
218    confl
82       cll
48       cse
Name: 5, Length: 298, dtype: object

In [17]:
original

,STATION #,REGION,Long Name,ORIGIN,X,Y,Short Name,Archive Index
Archive Index,,,,,,,,
77,21,Central Bay,Alameda,DWR Revised,561692.7,4180641.2,REaamc1,77.0
241,22,Central Bay,San Francisco Bay at Pier 17,DWR,553143.4,4184169.8,sfp17,241.0
74,23,Central Bay,San Francisco,DWR,547094.8,4184503.1,sffpx,74.0
185,24,Central Bay,San Francisco Bay at Northeast Shore Alcatraz ...,DWR,550895.2,4186802.8,alk,185.0
72,28,Central Bay,Tiburon Pier,DWR Revised,548873.4,4193835.1,REtibc1,72.0
...,...,...,...,...,...,...,...,...
63,86,Suisun Bay,Montezuma Slough at National Steel,DWR,597451.6,4219938.0,nsl,63.0
258,87,Suisun Bay,Montezuma Slough at Roaring River,DWR,597578.3,4216762.7,msl,258.0
218,88,Suisun Bay,Suisun Bay At Van Sickle Island,DWR,597605.9,4211894.6,confl,218.0
82,90,Suisun Bay,Collinsville,DWR,600858.7,4214644.1,cll,82.0
48,91,Suisun Bay,Sacramento River at Collinsville,DWR,600859.1,4214643.6,cse,48.0

In [18]:
# where do the short names differ
newnames=original['Short Name']
newnames

Archive Index
77     REaamc1
241      sfp17
74       sffpx
185        alk
72     REtibc1
        ...
63         nsl
258        msl
218      confl
82         cll
48         cse
Name: Short Name, Length: 298, dtype: object

In [20]:
~overlap.isin(newnames) # true means it is different

0
77      True
241    False
74     False
185    False
72      True
       ...
63     False
258    False
218    False
82     False
48     False
Name: 5, Length: 298, dtype: bool

In [21]:
sum(~overlap.isin(newnames))

90

In [22]:
newnames[~overlap.isin(newnames)]

Archive Index
77     REaamc1
72     REtibc1
381      54824
378      54755
379      54757
        ...
338      27344
58       REibs
256      REgod
257      REhun
254      REbll
Name: Short Name, Length: 90, dtype: object

# Add the stations that don't have an archive index and those with a short name that is