# filter run_27 salinity data: running into issues because added some stations partway through the run

In [1]:
import argparse
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
from vtools.functions.filter import cosine_lanczos
from vtools.data.vtime import days, hours, minutes

In [2]:
def filter_timeseries(tss, cutoff_period=hours(40)):
    #function comes from schimpy metricsplot.py script https://github.com/CADWRDeltaModeling/schimpy/blob/master/schimpy/metricsplot.py
    """ Filter time series

        Parameters
        ----------

        Returns
        -------
        list of vtools.data.timeseries.TimeSeries
            filtered time series
    """

    filtered = []
    ts=tss #try removing the loop for now
    if ts is None:
        filtered.append(None)
    else:
        ts_filtered = cosine_lanczos(ts.astype("float64"), cutoff_period=cutoff_period)
        ts_filtered.filtered = 'cosine_lanczos'
    return ts_filtered

# this file removes them

In [3]:
filepath="/expanse/lustre/scratch/jisrael/temp_project/run_schism/run_27/station_files/run_27_salinity_remove_newstations.txt"
nstations=405

In [4]:
columns = ['time']
#stations_no = [str(i) for i in range(nstations)]
#EDIT 11/18/2025: station columns should start with 1 NOT 0 to be consistent with the raw station data/ station.in file numbering 
stations_no = [str(i) for i in np.arange(1,nstations+1)]
columns = columns + stations_no
station = pd.read_csv(filepath, sep='\\s+', names=columns,dtype=np.float32)
station

,time,1,2,3,4,5,6,7,8,9,...,396,397,398,399,400,401,402,403,404,405
0,900.0,1.06,0.0729,0.0735,-10000.0,0.140,0.137,0.143,0.394,0.15,...,0.142,-999.0,-999.0,0.739,-999.0,0.0721,0.374,0.141,0.141,0.170
1,1800.0,1.06,0.0729,0.0735,-10000.0,0.140,0.137,0.143,0.394,0.15,...,0.142,-999.0,-999.0,0.739,-999.0,0.0721,0.375,0.141,0.141,0.170
2,2700.0,1.06,0.0729,0.0735,-10000.0,0.141,0.138,0.143,0.395,0.15,...,0.142,-999.0,-999.0,0.739,-999.0,0.0721,0.375,0.141,0.141,0.170
3,3600.0,1.06,0.0729,0.0735,-10000.0,0.141,0.138,0.143,0.396,0.15,...,0.142,-999.0,-999.0,0.740,-999.0,0.0721,0.375,0.142,0.141,0.170
4,4500.0,1.06,0.0729,0.0735,-10000.0,0.141,0.139,0.143,0.396,0.15,...,0.142,-999.0,-999.0,0.741,-999.0,0.0721,0.375,0.142,0.141,0.170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109819,98800000.0,5.00,0.0640,0.1480,-10000.0,0.262,0.334,0.405,0.212,3.35,...,0.357,-999.0,-999.0,2.360,-999.0,0.1460,1.000,0.454,0.273,0.331
109820,98800000.0,5.08,0.0641,0.1480,-10000.0,0.262,0.334,0.405,0.210,3.44,...,0.357,-999.0,-999.0,2.360,-999.0,0.1460,1.000,0.454,0.274,0.331
109821,98800000.0,5.14,0.0641,0.1480,-10000.0,0.262,0.334,0.405,0.208,3.50,...,0.357,-999.0,-999.0,2.360,-999.0,0.1460,1.000,0.454,0.274,0.330
109822,98800000.0,5.17,0.0641,0.1480,-10000.0,0.262,0.334,0.405,0.206,3.53,...,0.357,-999.0,-999.0,2.360,-999.0,0.1460,1.000,0.454,0.274,0.329
109823,98800000.0,5.18,0.0641,0.1480,-10000.0,0.262,0.334,0.405,0.205,3.53,...,0.357,-999.0,-999.0,2.360,-999.0,0.1460,1.000,0.454,0.275,0.328

# the problem is that at the end of the file the scientific notation got truncated: go back to the padded file

In [3]:
filepath="/expanse/lustre/scratch/jisrael/temp_project/run_schism/run_27/station_files/run_27_salinity_padded.txt"
nstations=408
timebasis='08-14-2018T00:00:00' 
startfilter='09-01-2018T00:00:00'

In [4]:
columns = ['time']
#stations_no = [str(i) for i in range(nstations)]
#EDIT 11/18/2025: station columns should start with 1 NOT 0 to be consistent with the raw station data/ station.in file numbering 
stations_no = [str(i) for i in np.arange(1,nstations+1)]
columns = columns + stations_no
station = pd.read_csv(filepath, sep='\\s+', names=columns,dtype=np.float32)
station

,time,1,2,3,4,5,6,7,8,9,...,399,400,401,402,403,404,405,406,407,408
0,900.0,1.05981,0.072932,0.073514,-9999.0,0.140204,0.137092,0.143006,0.393559,0.149575,...,0.738948,-999.0,0.072072,0.374339,0.141467,0.141364,0.169654,NaN,NaN,NaN
1,1800.0,1.05903,0.072933,0.073519,-9999.0,0.140381,0.137255,0.142985,0.394150,0.149561,...,0.739228,-999.0,0.072073,0.374772,0.141482,0.141365,0.169639,NaN,NaN,NaN
2,2700.0,1.05788,0.072935,0.073528,-9999.0,0.140649,0.137562,0.142952,0.394719,0.149564,...,0.739496,-999.0,0.072075,0.375022,0.141499,0.141371,0.169630,NaN,NaN,NaN
3,3600.0,1.05645,0.072937,0.073537,-9999.0,0.141008,0.138132,0.142939,0.395620,0.149544,...,0.739892,-999.0,0.072076,0.374940,0.141516,0.141378,0.169628,NaN,NaN,NaN
4,4500.0,1.05577,0.072939,0.073540,-9999.0,0.141416,0.138743,0.142896,0.396423,0.149510,...,0.740549,-999.0,0.072077,0.374753,0.141532,0.141385,0.169634,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109819,98838000.0,5.00459,0.064049,0.148477,-9999.0,0.262114,0.334248,0.404953,0.211581,3.353930,...,2.359540,-999.0,0.145801,1.002560,0.453801,0.273183,0.331369,0.067532,0.079517,0.097319
109820,98838896.0,5.08459,0.064061,0.148170,-9999.0,0.262181,0.334250,0.404908,0.209756,3.439600,...,2.360320,-999.0,0.145820,1.001150,0.453787,0.273553,0.330564,0.067402,0.079511,0.097291
109821,98839800.0,5.14329,0.064071,0.147936,-9999.0,0.262256,0.334251,0.404889,0.208016,3.497780,...,2.360540,-999.0,0.145843,1.000300,0.453766,0.273916,0.329807,0.067289,0.079505,0.097267
109822,98840704.0,5.17459,0.064079,0.147781,-9999.0,0.262338,0.334251,0.404890,0.206380,3.529890,...,2.359490,-999.0,0.145872,1.000270,0.453742,0.274264,0.329038,0.067195,0.079500,0.097247
109823,98841600.0,5.17649,0.064085,0.147712,-9999.0,0.262424,0.334249,0.404905,0.205035,3.529330,...,2.356890,-999.0,0.145904,1.000850,0.453713,0.274586,0.328158,0.067118,0.079496,0.097231

In [5]:
#fill nans
station = station.fillna(-9999)
timedelta = [pd.Timedelta(i, unit = 's') for i in station.time]
timestamp = pd.Series([pd.to_datetime(timebasis) + i for i in timedelta])
timestamp

0        2018-08-14 00:15:00
1        2018-08-14 00:30:00
2        2018-08-14 00:45:00
3        2018-08-14 01:00:00
4        2018-08-14 01:15:00
                 ...
109819   2021-09-30 23:00:00
109820   2021-09-30 23:14:56
109821   2021-09-30 23:30:00
109822   2021-09-30 23:45:04
109823   2021-10-01 00:00:00
Length: 109824, dtype: datetime64[us]

In [6]:
timestamp.dt

In [7]:
#added 07/01 on Savio
roundtime=timestamp.dt.round(freq='900s')
station['time'] = roundtime
station.set_index("time",inplace=True)
station=station.asfreq('900s')

In [8]:
station

,1,2,3,4,5,6,7,8,9,10,...,399,400,401,402,403,404,405,406,407,408
time,,,,,,,,,,,,,,,,,,,,,
2018-08-14 00:15:00,1.05981,0.072932,0.073514,-9999.0,0.140204,0.137092,0.143006,0.393559,0.149575,0.149582,...,0.738948,-999.0,0.072072,0.374339,0.141467,0.141364,0.169654,-9999.000000,-9999.000000,-9999.000000
2018-08-14 00:30:00,1.05903,0.072933,0.073519,-9999.0,0.140381,0.137255,0.142985,0.394150,0.149561,0.149566,...,0.739228,-999.0,0.072073,0.374772,0.141482,0.141365,0.169639,-9999.000000,-9999.000000,-9999.000000
2018-08-14 00:45:00,1.05788,0.072935,0.073528,-9999.0,0.140649,0.137562,0.142952,0.394719,0.149564,0.149566,...,0.739496,-999.0,0.072075,0.375022,0.141499,0.141371,0.169630,-9999.000000,-9999.000000,-9999.000000
2018-08-14 01:00:00,1.05645,0.072937,0.073537,-9999.0,0.141008,0.138132,0.142939,0.395620,0.149544,0.149550,...,0.739892,-999.0,0.072076,0.374940,0.141516,0.141378,0.169628,-9999.000000,-9999.000000,-9999.000000
2018-08-14 01:15:00,1.05577,0.072939,0.073540,-9999.0,0.141416,0.138743,0.142896,0.396423,0.149510,0.149521,...,0.740549,-999.0,0.072077,0.374753,0.141532,0.141385,0.169634,-9999.000000,-9999.000000,-9999.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-09-30 23:00:00,5.00459,0.064049,0.148477,-9999.0,0.262114,0.334248,0.404953,0.211581,3.353930,3.524310,...,2.359540,-999.0,0.145801,1.002560,0.453801,0.273183,0.331369,0.067532,0.079517,0.097319
2021-09-30 23:15:00,5.08459,0.064061,0.148170,-9999.0,0.262181,0.334250,0.404908,0.209756,3.439600,3.628240,...,2.360320,-999.0,0.145820,1.001150,0.453787,0.273553,0.330564,0.067402,0.079511,0.097291
2021-09-30 23:30:00,5.14329,0.064071,0.147936,-9999.0,0.262256,0.334251,0.404889,0.208016,3.497780,3.712550,...,2.360540,-999.0,0.145843,1.000300,0.453766,0.273916,0.329807,0.067289,0.079505,0.097267
2021-09-30 23:45:00,5.17459,0.064079,0.147781,-9999.0,0.262338,0.334251,0.404890,0.206380,3.529890,3.771900,...,2.359490,-999.0,0.145872,1.000270,0.453742,0.274264,0.329038,0.067195,0.079500,0.097247
2021-10-01 00:00:00,5.17649,0.064085,0.147712,-9999.0,0.262424,0.334249,0.404905,0.205035,3.529330,3.808380,...,2.356890,-999.0,0.145904,1.000850,0.453713,0.274586,0.328158,0.067118,0.079496,0.097231

In [9]:
#update 11/18/2025: trim the data to where you want to start filtering(e.g. after the nudging/ model warm-up), due to the 40 hr cosine filter end up losing the first 100 hours (400 samples of 15 minute data) so actually trim 40 hours back of this date
fstart=pd.to_datetime(startfilter)-pd.Timedelta(hours=100)
if fstart < pd.to_datetime(timebasis):
    print('Need to choose later time to start filtering')
station2filt=station[fstart:]

In [10]:
station2filt

,1,2,3,4,5,6,7,8,9,10,...,399,400,401,402,403,404,405,406,407,408
time,,,,,,,,,,,,,,,,,,,,,
2018-08-27 20:00:00,2.19877,0.063910,0.079431,-9999.0,0.164474,0.231836,0.267198,0.330791,0.457913,0.459038,...,1.17215,-999.0,0.077573,0.686157,0.311618,0.147980,0.231209,-9999.000000,-9999.000000,-9999.000000
2018-08-27 20:15:00,2.14002,0.063892,0.079356,-9999.0,0.164698,0.232248,0.268142,0.329918,0.418772,0.420924,...,1.17408,-999.0,0.077577,0.685996,0.310507,0.148455,0.236684,-9999.000000,-9999.000000,-9999.000000
2018-08-27 20:30:00,2.05142,0.063875,0.079277,-9999.0,0.165082,0.232356,0.269117,0.327865,0.376219,0.380542,...,1.17577,-999.0,0.077581,0.685964,0.309471,0.148944,0.240655,-9999.000000,-9999.000000,-9999.000000
2018-08-27 20:45:00,1.95348,0.063860,0.079188,-9999.0,0.165563,0.232152,0.270068,0.324686,0.334319,0.339907,...,1.17723,-999.0,0.077584,0.685908,0.308720,0.149383,0.243618,-9999.000000,-9999.000000,-9999.000000
2018-08-27 21:00:00,1.86472,0.063847,0.079091,-9999.0,0.166089,0.231784,0.270851,0.320767,0.296255,0.300337,...,1.17855,-999.0,0.077588,0.685759,0.308208,0.149753,0.246271,-9999.000000,-9999.000000,-9999.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-09-30 23:00:00,5.00459,0.064049,0.148477,-9999.0,0.262114,0.334248,0.404953,0.211581,3.353930,3.524310,...,2.35954,-999.0,0.145801,1.002560,0.453801,0.273183,0.331369,0.067532,0.079517,0.097319
2021-09-30 23:15:00,5.08459,0.064061,0.148170,-9999.0,0.262181,0.334250,0.404908,0.209756,3.439600,3.628240,...,2.36032,-999.0,0.145820,1.001150,0.453787,0.273553,0.330564,0.067402,0.079511,0.097291
2021-09-30 23:30:00,5.14329,0.064071,0.147936,-9999.0,0.262256,0.334251,0.404889,0.208016,3.497780,3.712550,...,2.36054,-999.0,0.145843,1.000300,0.453766,0.273916,0.329807,0.067289,0.079505,0.097267
2021-09-30 23:45:00,5.17459,0.064079,0.147781,-9999.0,0.262338,0.334251,0.404890,0.206380,3.529890,3.771900,...,2.35949,-999.0,0.145872,1.000270,0.453742,0.274264,0.329038,0.067195,0.079500,0.097247
2021-10-01 00:00:00,5.17649,0.064085,0.147712,-9999.0,0.262424,0.334249,0.404905,0.205035,3.529330,3.808380,...,2.35689,-999.0,0.145904,1.000850,0.453713,0.274586,0.328158,0.067118,0.079496,0.097231

In [11]:
station2filt.isnull().sum().max()

np.int64(0)

In [12]:
station_filt = filter_timeseries(station2filt)

In [13]:
station_filt

,1,2,3,4,5,6,7,8,9,10,...,399,400,401,402,403,404,405,406,407,408
time,,,,,,,,,,,,,,,,,,,,,
2018-08-27 20:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-08-27 20:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-08-27 20:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-08-27 20:45:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-08-27 21:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-09-30 23:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-09-30 23:15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-09-30 23:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-09-30 23:45:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-10-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
station_filt.to_csv('/expanse/lustre/scratch/jisrael/temp_project/run_schism/run_27/station_files/run_27_salinity_padded_filt.csv')

In [ ]:
/expanse/lustre/scratch/jisrael/temp_project/run_schism/run_27/station_files